### PR TITLE
Feat/initial devops extension

### PR DESCRIPTION
**Pull request by dgcaron**
This is the devops extension i drafted. these step works on Linux, Windows and mac agents. you can use the extension like this in yaml pipelines:

this step installs infracost in the toolchain. if the version already exists (if people run self hosted agents for instance) this step is skipped automatically. it is similar (actually I looked at their implementation) to the terraform extension for devops
```yaml
steps:
- task: InfracostInstaller@0
  inputs:
    infracostVersion: '0.9.10'
```

this step runs a breakdown on a terraform plan
```yaml
- task: InfracostTask@0
  inputs:
    command: 'breakdown'
    commandOptions: '--path $(System.DefaultWorkingDirectory)/develop.changes.json --format json'
```

this step is to combine multiple results output the data to the extension: 
```yaml
- task: InfracostTask@0
  inputs:
    command: 'output'
    commandOptions: '--path $(System.DefaultWorkingDirectory)/develop.costs.json --format html'
    outputFile: '$(Build.ArtifactStagingDirectory)/develop.html'
```
this is not 100% perfect yet. but I think it is an ok start. 

the hub now shows a report created with the output but we could push a report for each commit in a PR if we make the collection equal to the pr id.

### CODE REVIEW

**Comment by tim775** [comment]
Thanks for this it is a great start!  What do you think if I move it into an "experimental" branch until we get a change to polish it?

**Comment by dgcaron** [comment]
Yes, that would be fine!

**Comment by hugorut** [comment]
Hey @dgcaron we're just starting to play around with this again. Thanks it's great! We're currently evaluating how we migrate our azure devops pipeline template to something more composable, resembling the recent work we’ve done with [GitHub actions](https://github.com/infracost/actions). In order to do this we're thinking what's the best way to pre-bundle deps like infracost and provide a simpler way for people to work with it in pipeline steps. We're evaluating tasks alongside container jobs and wanted to get your point of view on the merits/downsides of both approaches? In your experience what works best & what is a more adopted approach?

**Comment by dgcaron** [comment]
Hi! I started on this earlier but got sick and the normal work started to pile up. I am totally willing to discuss but also do some off the work if that is needed. I think the way the GH action works, works equally well for Azure DevOps. 

So have an installertask and a commenttask. Running infracost can be done from script tasks as thaf would be way more flexible. The installer adds the binary to the Path so it will be available in next steps in the same stage. One thing the installer is missing is the ability to always install the latest version of infracost.

**Comment by hugorut** [comment]
@dgcaron Amazing, thanks for your efforts 🚀 🚀 ! Yes this is how we were thinking exactly how it could work with a `installtask` and `commenttask`. This sounds very promising. Let me discuss with the team as we're still in the evaluation phase, I'll loop back to you early next week and get your input on a few things. It would be great to get your expertise on this work.

**Comment by hugorut** [comment]
Hey @dgcaron  - just keeping you in the loop. Thanks to your input we're starting work on the composable tasks based approach! We'd love your feedback and input once we have an initial draft together. Hopefully by the beginning of next week.

**Comment by dgcaron** [comment]
This is great! If you can share an initial (private) version with my organisation I can give it a try.

**Comment by hugorut** [comment]
Amazing, thanks @dgcaron ❤️❤️❤️🎺🎺🎺

**Pull request merged**
