### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by aliscott**
* Add instructions for adding the Terraform and Infracost tasks to the organization
* Add separate quick starts for Azure Repos and GitHub Repos
* Add inline comments to examples
* Add section linking to the different task docs
* Merge the README and overview so we have the same docs for GitHub and the Azure DevOps marketplace

### CODE REVIEW

**Comment by aliscott** [comment]
@alikhajeh1 can you have a quick look at the 'Quick start' section to see if it makes sense to split it in this way for Azure Repos and GitHub Repos. I did it in this way so the user didn't need to jump around  Another option I was thinking was just to repeat the same steps 1-3 for each.

Also,`overview.md` can't be renamed for it to appear in the Azure DevOps marketplace. I'm unsure if the quick start should be repeated here along with the examples, or if it should just link to the GitHub readme (what I've done currently). Maybe something to check in the user tests is where they would usually discover the extensions.

**Comment by vdmgolub** [comment]
@aliscott FYI, I've rebased the branch to resolve conflicts and pick up the latest changes.

**Comment by alikhajeh1** [comment]
@aliscott the readme was great! I liked the flow. Should overview.md just link to the readme and we can move the contents into another page that's linked to from the readme's Tasks section? We've seen from user testing that people just jump to code blocks so it's very easy to get stuck trying to DIY it from the overview page and miss the readme with examples.

**Comment by aliscott** [comment]
> Should overview.md just link to the readme and we can move the contents into another page that's linked to from the readme's Tasks section?

@alikhajeh1 Another option is just to `cp README.md overview.md` since the overview.md is what is shown here: https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks (example for Terraform tasks). That way it's the same onboarding if the user is coming from GitHub or the Azure Marketplace.

**Comment by alikhajeh1** [comment]
+1 on `cp README.md overview.md`

**Pull request merged**
